version: "3.8"
name: aid-compass
services:
#  web:
#    image: nginx
#    container_name: aid-compass-nginx
#    volumes:
#      - ./templates:/etc/nginx/templates
#    ports:
#      - "8443:443"
#    environment:
#      - NGINX_HOST=localhost
#      - NGINX_PORT=443
#      - API_HOST=api
#      - API_PORT=443

  aid-compass-api:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: aid-compass-api
    ports:
      - "8443:8443"
    env_file:
      - .env

  aid-compass-postgresql:
    image: postgres:16.1-alpine3.19
    container_name: aid-compass-postgresql
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: aid_compass_database
    volumes:
      - ../db_schemas/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
    ports:
      - "5432:5432"

  aid-compass-redis:
    image: redis
    container_name: aid-compass-redis
    networks:
      - default
    ports:
      - "6379:6379"

#  aid-compass-prometheus:
#    image: prom/prometheus:latest
#    container_name: aid-compass-prometheus
#    networks:
#      - default
#    volumes:
#      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#      - ./prometheus/prometheus_token.txt:/etc/prometheus/prometheus_token.txt
#    ports:
#      - "9090:9090"
#
#  aid-compass-grafana:
#    image: grafana/grafana:latest
#    container_name: aid-compass-grafana
#    networks:
#      - default
#    ports:
#      - "3000:3000"
#
#  aid-compass-kafka:
#    image: apache/kafka:latest
#    container_name: aid-compass-kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_NODE_ID: 1
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

networks:
  default: