version: "3.8"
name: aid-compass
services:
  aid-compass-api:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: aid-compass-api
    ports:
      - "8443:8443"
    env_file:
      - .env

  aid-compass-postgresql:
    image: postgres:16.1-alpine3.19
    container_name: aid-compass-postgresql
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: aid_compass_database
    volumes:
      - ../db_schemas/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
    ports:
      - "5432:5432"

  aid-compass-redis:
    image: redis
    container_name: aid-compass-redis
    networks:
      - default
    ports:
      - "6379:6379"

  aid-compass-prometheus:
    image: prom/prometheus:latest
    container_name: aid-compass-prometheus
    networks:
      - default
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus_token.txt:/etc/prometheus/prometheus_token.txt
    ports:
      - "9090:9090"

  aid-compass-grafana:
    image: grafana/grafana:latest
    container_name: aid-compass-grafana
    networks:
      - default
    ports:
      - "3000:3000"

networks:
  default: